### ISSUE TITLE
memory leak when dumping stats in json format

### ISSUE THREAD

**Issue by flabatut** [acassen/keepalived#1905]
**Describe the bug**
While keepalived running, sending signal in order to dump stats in json format, on a regular basis, leads keepalived to consume memory incrementally, without releasing it, causing memory exhaustion. Problem isn't reproducible when dumping stats using text format. It consumes approx 7MB/h when using json format, wheras memory consumption remains steady without json format. See screenshot:

![Screenshot 2021-05-19 at 15 48 34](https://user-images.githubusercontent.com/31963611/118839814-1da09d00-b8c7-11eb-912c-c9c3f04d18c8.png)

**To Reproduce**
* run keepalived with options "--vrrp , --log-console , --dont-fork" and one vip configured (see config below)
* run [keepalived_exporter](https://github.com/gen2brain/keepalived_exporter) with option "-ka.json" (alternatively a scheduled shell script sending signal should do the trick)
* use any monitoring tool to graph memory usage

Any steps necessary to reproduce the behaviour:

**Expected behavior**
whatever the stats dump format, memory usage should remain the same (memory freed once unused)

**Keepalived version**
```
# keepalived -v
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 5.4.0-1032-kvm #33-Ubuntu SMP Thu Jan 14 22:53:00 UTC 2021

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

**Distro:**
 - Name: Ubuntu
 - Version: 5.4.0-1032-kvm #33-Ubuntu SMP Thu Jan 14 22:53:00 UTC 2021 x86_64 GNU/Linux
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**

* run in a container embedded in a pod, conjointly with another container running the metrics exporter.
* requires [NET_ADMIN](https://packetpushers.net/vrrp-linux-using-keepalived-2/) capability for keepalived and [SYS_PTRACE](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/#configure-a-pod) for exporter (ref: https://man7.org/linux/man-pages/man7/capabilities.7.html)
* use [hostNetwork](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces) and [shareProcessNamespace](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/)
* Manifest sample:
```
apiVersion: v1
kind: Pod
metadata:
  name: keepalived
spec:
  containers:
  - image: keepalived_exporter:latest
    name: exporter
    ports:
    - containerPort: 9650
      hostPort: 9650
      protocol: TCP
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    volumeMounts:
    - mountPath: /tmp
      name: stats
  - args:
    - --vrrp
    - --log-detail
    - --log-console
    - --dont-fork
    image: keepalived:latest
    name: keepalived
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    volumeMounts:
    - mountPath: /etc/keepalived/keepalived.conf
      name: config
      subPath: keepalived.conf
    - mountPath: /tmp
      name: stats
  hostNetwork: true
  shareProcessNamespace: true
  volumes:
  - emptyDir: {}
    name: stats
  - configMap:
      defaultMode: 420
      name: keepalived-configmap
    name: config
```

**Configuration file:**
```
vrrp_instance VI_1 {
  interface eth0
  virtual_router_id 23
  nopreempt
  advert_int 1 # VRRP Advert interval in seconds
  authentication {
    auth_type PASS
    auth_pass xxxx
  }
  virtual_ipaddress {
    192.168.0.1/32
  }
}
```

**System Log entries**
```
Mon May 10 21:49:15 2021: Starting Keepalived v2.0.10 (11/12,2018)
Mon May 10 21:49:15 2021: Running on Linux 5.4.0-1032-kvm #33-Ubuntu SMP Thu Jan 14 22:53:00 UTC 2021 (built for Linux 4.18.20)
Mon May 10 21:49:15 2021: Command line: '/usr/sbin/keepalived' '--vrrp' '--log-detail' '--log-console' '--dont-fork'
Mon May 10 21:49:15 2021: Opening file '/etc/keepalived/keepalived.conf'.
Mon May 10 21:49:15 2021: Starting VRRP child process, pid=22
Mon May 10 21:49:15 2021: Registering Kernel netlink reflector
Mon May 10 21:49:15 2021: Registering Kernel netlink command channel
Mon May 10 21:49:15 2021: Opening file '/etc/keepalived/keepalived.conf'.
Mon May 10 21:49:15 2021: Assigned address 192.168.0.2 for interface eth0
Mon May 10 21:49:15 2021: Assigned address xxxx for interface eth0
Mon May 10 21:49:15 2021: Registering gratuitous ARP shared channel
Mon May 10 21:49:15 2021: (VI_1) removing VIPs.
Mon May 10 21:49:15 2021: (VI_1) Entering BACKUP STATE (init)
Mon May 10 21:49:15 2021: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(10,11)]
Mon May 10 21:49:15 2021: (VI_1) Backup received priority 0 advertisement
Mon May 10 21:49:16 2021: (VI_1) Receive advertisement timeout
Mon May 10 21:49:16 2021: (VI_1) Entering MASTER STATE
Mon May 10 21:49:16 2021: (VI_1) setting VIPs.
Mon May 10 21:49:16 2021: Sending gratuitous ARP on eth0 for 192.168.0.1
Mon May 10 21:49:16 2021: (VI_1) Sending/queueing gratuitous ARPs on eth0 for 192.168.0.1
Mon May 10 21:49:16 2021: Sending gratuitous ARP on eth0 for 192.168.0.1
...
Tue May 18 14:17:25 2021: Printing VRRP as json for process(25455) on signal
Tue May 18 14:17:35 2021: Printing VRRP as json for process(25455) on signal
Tue May 18 14:17:35 2021: Printing VRRP as json for process(25455) on signal
Tue May 18 14:17:35 2021: Printing VRRP as json for process(25455) on signal
Tue May 18 14:17:45 2021: Printing VRRP as json for process(25455) on signal
...
```

**Did keepalived coredump?**
n/a
